main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('motorcycles/', views.motorcycles_index, name='index'),
  path('motorcycles/<int:motorcycle_id>/', views.motorcycles_detail, name='detail'),
  path('motorcycles/create/', views.MotorcycleCreate.as_view(), name='motorcycles_create'),
  path('motorcycles/<int:pk>/update/', views.MotorcycleUpdate.as_view(), name='motorcycles_update'),
  path('motorcycles/<int:pk>/delete/', views.MotorcycleDelete.as_view(), name='motorcycles_delete'),
  path('motorcycles/<int:motorcycle_id>/assoc_acc/<int:acc_id>/', views.assoc_acc, name='assoc_acc'),
  path('motorcycles/<int:motorcycle_id>/unassoc_acc/<int:acc_id>/', views.unassoc_acc, name='unassoc_acc'),
  path('motorcycles/<int:motorcycle_id>/add_photo/', views.add_photo, name='add_photo'),
  path('accs/', views.AccList.as_view(), name='accs_index'),
  path('accs/<int:pk>/', views.AccDetail.as_view(), name='accs_detail'),
  path('accs/create/', views.AccCreate.as_view(), name='accs_create'),
  path('accs/<int:pk>/update/', views.AccUpdate.as_view(), name='accs_update'),
  path('accs/<int:pk>/delete/', views.AccDelete.as_view(), name='accs_delete'),
  path('accounts/signup', views.signup, name='signup'),
]

motorcycles/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

MAINTENANCE = (
  ('Oil', 3000),
  ('Chain', 500),
  ('Tires', 7000)
)

class Acc(models.Model):
  name = models.CharField(max_length=100)
  size = models.CharField(max_length=100)
  color = models.CharField(max_length=100)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
      return reverse("accs_detail", kwargs={'pk': self.id})
      

class Motorcycle(models.Model):
  brand = models.CharField(max_length=100)
  model = models.CharField(max_length=100)
  style = models.CharField(max_length=100)
  year = models.IntegerField()
  color = models.CharField(max_length=100)
  mileage = models.IntegerField(default=100)
  accs = models.ManyToManyField(Acc)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  
  def __str__(self):
    return f'A {self.brand} {self.model}'

  def get_absolute_url(self):
      return reverse("detail", kwargs={"motorcycle_id": self.id})
  
class Photo(models.Model):
  url = models.CharField(max_length=200)
  motorcycle = models.ForeignKey(Motorcycle, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for motorcycle_id: {self.motorcycle_id} @{self.url}"

class maint(models.Model):
  done = models.IntegerField()
  maintenance = models.CharField(
    max_length=50,
    choices=MAINTENANCE,
    default=MAINTENANCE[0][0],
  )
  motorcycle = models.ForeignKey(Motorcycle, on_delete=models.CASCADE)
  def __str__(self):
    return f"Maintenance due in x miles"

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3
from .models import Motorcycle, Acc, Photo

S3_BASE_URL = 'https://s3-us-east-2.amazonaws.com/'
BUCKET = 'cat-image-collector'

# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def motorcycles_index(request):
  motorcycles = Motorcycle.objects.all()
  return render(request, 'motorcycles/index.html', {'motorcycles': motorcycles})

@login_required
def motorcycles_detail(request, motorcycle_id):
  motorcycle = Motorcycle.objects.get(id=motorcycle_id)
  accs_not_included = Acc.objects.exclude(id__in = motorcycle.accs.all().values_list('id'))

  return render(request, 'motorcycles/detail.html', { 
    'motorcycle': motorcycle , 'accs': accs_not_included
  })

class MotorcycleCreate(LoginRequiredMixin, CreateView):
  model = Motorcycle
  fields = '__all__'

class MotorcycleUpdate(LoginRequiredMixin, UpdateView):
  model = Motorcycle
  fields = '__all__'

class MotorcycleDelete(LoginRequiredMixin, DeleteView):
  model = Motorcycle
  success_url = '/motorcycles/'

@login_required
def assoc_acc(request, motorcycle_id, acc_id):
  Motorcycle.objects.get(id=motorcycle_id).accs.add(acc_id)
  return redirect('detail', motorcycle_id=motorcycle_id)

@login_required
def unassoc_acc(request, motorcycle_id, acc_id):
  Motorcycle.objects.get(id=motorcycle_id).accs.remove(acc_id)
  return redirect('detail', motorcycle_id=motorcycle_id)

@login_required
def add_photo(request, motorcycle_id):
  	# photo-file was the "name" attribute on the <input type="file">
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    # need a unique "key" for S3 / needs image file extension too
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    # just in case something goes wrong
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      # build the full url string
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      # we can assign to motorcycle_id or motorcycle (if you have a motorcycle object)
      photo = Photo(url=url, motorcycle_id=motorcycle_id)
      photo.save()
    except:
      print('An error occurred uploading file to S3')
  return redirect('detail', motorcycle_id=motorcycle_id)

class AccList(LoginRequiredMixin, ListView):
  model = Acc

class AccDetail(LoginRequiredMixin, DetailView):
  model = Acc

class AccCreate(LoginRequiredMixin, CreateView):
  model = Acc
  fields = '__all__'

class AccUpdate(LoginRequiredMixin, UpdateView):
  model = Acc
  fields = ['size', 'color']

class AccDelete(LoginRequiredMixin, DeleteView):
  model = Acc
  success_url = '/accs/'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user'form object
    # that include the data form browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - please try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Motorcycle Collector</h1>
<hr />
<p>Hire the Motorcyle Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Motorcycle Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Motorcycle Collector</a></li>
        </ul>
        <ul class="right">
          <li class="nav-link"><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li class="nav-link"><a href="{% url 'index' %}">Motorcycles</a></li>
            <li class="nav-link"><a href="{% url 'motorcycles_create' %}">Add Motorcycle</a></li>
            <li><a href="{% url 'accs_create' %}">Add an Accessory</a></li>
            <li><a href="{% url 'accs_index' %}">View Accessories</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2020 Motorcycle Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Justin's Toys</h1>

{% endblock %}

main_app/templates/main_app/acc_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Accessory</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'accs_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/acc_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Accessory Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ acc }}</span>
        <p>Color: {{ acc.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'accs_update' acc.id %}">Edit</a>
        <a href="{% url 'accs_delete' acc.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/acc_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Accesory</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/acc_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Accessory List</h1>

{% for acc in acc_list %}
  <a href="{% url 'accs_detail' acc.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ acc }}</span>
            <p>Color: {{ acc.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/accessory_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Accesory</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/accessory_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Accessory List</h1>

{% for acc in acc_list %}
  <a href="{% url 'accs_detail' accesory.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ acc }}</span>
            <p>Color: {{ acc.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/motorcycle_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Motorcycle</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a class="btn" href="{% url 'detail' motorcycle.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/motorcycle_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
    <h1>Edit <span class="teal-text">{{object}}</span></h1>
  {% else %}
    <h1>Add Motorcycle</h1>
  {% endif %}

    <div class="card">
      <form action="" method="post">
        <!-- Django requires the following for security purposes -->
        {% csrf_token %}
        <table>
          <!-- Render the inputs inside of <tr>s & <td>s -->
          {{ form.as_table }}
        </table>
        <div class="center">
        <input type="submit" value="Submit!" class="btn">
        </div>
      </form>
    </div>
{% endblock %}

main_app/templates/motorcycles/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Motorcycle Details</h1>

<div class="card">
  <div class="card-content">
        <span class="card-title">{{ motorcycle.brand }} {{ motorcycle.model }}</span>
        <p>Year: {{ motorcycle.year }}</p>
        <p>Style: {{ motorcycle.style }}</p>
        <p>Color: {{ motorcycle.color }}</p>
          <div class="card-action">
            <a href="{% url 'motorcycles_update' motorcycle.id %}">Edit</a>
            <a href="{% url 'motorcycles_delete' motorcycle.id %}">Delete</a>
          </div>
      </div>
</div>

{% comment %} <div class="col s6">
    <form action="{% url 'add_oil_due' motorcycle.id %}" method="post">
      {% csrf_token %}
      {{ oil_due_form.as_p }}
      <input type="submit" class="btn" value="Oil Due">
    </form>
    <br>
    {% if motorcycle.oil_due %}
      <div class="card-panel teal-text center-align">{{motorcycle}} is not due for an oil change.</div>
    {% else %}
      <div class="card-panel red-text center-align">{{motorcycle}} is due for an oil change.</div>
    {% endif %}
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Changed</th></tr>
      </thead>
      <tbody>
        {% for feeding in cat.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div> {% endcomment %}

<hr>

{% for photo in motorcycle.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
      <form action="{% url 'add_photo' motorcycle.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
    </form>
    {% comment %} </div> {% endcomment %}
  

<div class="row">
  <div class="col s6">
    <h3>Equiped Accessories</h3>
    {% if motorcycle.accs.count %}
      {% for acc in motorcycle.accs.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ acc.color }}">{{ acc.color }}</span> {{ acc.name }} {{ acc.size}}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_acc' motorcycle.id acc.id %}" method="post">
                {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Accessories :(</h5>
    {% endif %}
  </div>
  <!-- Available accessories will come after this line -->
    <div class="col s6">
    <h3>Available Accessories</h3>
    {% if accs.count %}
      {% for acc in accs.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ acc.color }}">{{ acc.color }}</span> {{ acc.name }} {{ acc.size}}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_acc' motorcycle.id acc.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{motorcycle}} Already Has All Accessories Available</h5>
    {% endif %}
  </div>
</div>

{% endblock %}

main_app/templates/motorcycles/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Motorcycle List</h1>
<hr />

{% for motorcycle in motorcycles %}
  <div class="card">
    <a href="{% url 'detail' motorcycle.id %}">
      <div class="card-content">
        <span class="card-title">{{ motorcycle.brand }} {{ motorcycle.model }}</span>
        <p>Year: {{ motorcycle.year }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}